[package]
name = "factory_app"
version.workspace = true
edition.workspace = true

[dependencies]
bevy.workspace = true
bevy_input = { version = "0.19.1", features = ["serialize"] }
factory_data.workspace = true
factory_sim.workspace = true
ron = "0.12.2"
serde = { version = "1.0.228", features = ["derive"] }
chrono = { version = "0.4.41", default-features = false, features = ["clock"] }

[target.'cfg(unix)'.dependencies]
libc = "0.2.189"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_Storage_FileSystem"] }

[dev-dependencies]
factory_data = { workspace = true, features = ["test-utils"] }
